### ISSUE TITLE
Cannot move map while token moves

### ISSUE THREAD

**Issue by Nordiii** [wsaunders1014/ShowDragDistance#12]
I noticed that I cannot move the map when a Token is getting moved, which can get annoying.
How to reproduce:

1. Fresh World in 5e with just this module enabled
2. Create a Scene and place a token on it
3. Move the map with the right mouse button
4. Use wasd to move the token

=> Map movement stops

**Comment by wsaunders1014** [comment]
I believe this is fixed now.
