### ISSUE TITLE
Cannot move Map Markers (e.g. Journal Entries)

### ISSUE THREAD

**Issue by sdenec** [wsaunders1014/ShowDragDistance#16]
When placing map markers - e.g. drag and drop a journal entry onto a scene - the markers can't be relocated. Upon dropping the marker in its new location it doesn't snap to the grid, shows a ghostly copy of it self and becomes unselectable/unclickable. Upon reloading foundry the icon appears as normal but when dragged around the issue resurfaces upon droppping it. 

foundry 0.6.6 
with dnd5e 0.96

**Comment by wsaunders1014** [comment]
Please try 2.0.3, the issue should now be resolved.

**Comment by sdenec** [comment]
Fixed, perfect! Thanks for your fast reply and great module!
