### ISSUE TITLE
Suggestion: Easy way to cancel movement while left click-dragging

### ISSUE THREAD

**Issue by Nerull91** [wsaunders1014/ShowDragDistance#18]
Unless I missed it, there is no way for a player to "cancel" their movement once they started left-click dragging their token and making a path. They have to make a waypoint back to their original position and release the left click and the token will follow the path and move back to the original position.

**Comment by wsaunders1014** [comment]
Please update to 2.0.3, pressing X will now cancel waypoints and then cancel drag if there are no more waypoints.

**Comment by Nerull91** [comment]
Excellent thanks!
