### ISSUE TITLE
Dragging tiles seems broken

### ISSUE THREAD

**Issue by kristianserrano** [wsaunders1014/ShowDragDistance#19]
I think version 2.x has possibly broken dragging tiles. When using with Card Support (Unofficial), once a tile is released, it cannot be selected again nor can it be dragged.

**Comment by wsaunders1014** [comment]
Please try updating to 2.0.3 and let me know if the issue is resolved.

**Comment by kristianserrano** [comment]
That fixed it! Thank you.
