### ISSUE TITLE
Movespeed not recognized with Obsidian

### ISSUE THREAD

**Issue by CaelReader** [wsaunders1014/ShowDragDistance#20]
The new feature where it highlights tiles beyond your movement speed doesn't work properly with Obsidian sheets (just assumes 30ft no matter what), since it uses its own values for speed on its sheets. Would like a way to turn this feature off to avoid confusion, if proper compatibility is too much of a hassle.

**Comment by wsaunders1014** [comment]
This is probably fixed now. I didn't want to install Obsidian and migrate my data to test. You can also now configure the location of where the speed is stored in the settings.
