### ISSUE TITLE
Drag distance path not being cleared upon right-clicking to cancel movement

### ISSUE THREAD

**Issue by bluesatin** [wsaunders1014/ShowDragDistance#25]
# Information
Foundry Virtual Tabletop — 0.6.6
Show Drag Distance — 1.1.3

# Issue
When dragging a token with 'Show Path by Default' enabled, if you right-click to cancel the movement and the token is returned back to its original position, the drag-distance overlay isn't cleared properly and will continue to exist.

This uncleared 'stuck' path acts rather funky, and sometimes interacts with other sort of measurements and stuff to have duplicate paths shown and have it teleport around or sometimes just have a single start/end dot being shown following the cursor.

This uncleared 'stuck' path can be cleared by starting a new drag on a token and releasing normally.

# Reproducing
1. Enable 'Showing Distance on Drag'.
2. Enable 'Show Path by Default'.
3. Start dragging a token so that a path is shown.
4. Right-click while still dragging the token (to cancel the drag, and return the token back to its original position).
5. The path won't be cleared and will continue to exist until a new drag is started.

----

Thanks for your time and hard-work! :)

**Comment by wsaunders1014** [comment]
Is there a specific reason you're not updating to the latest version? If you're on 1.1.3, you'll need to uninstall it first or the auto updater won't work.

**Comment by bluesatin** [comment]
Ah whoops, didn't realise there was something stopping the module being updated via the 'Check Update' functionality.

I'll have to make sure I actually check version numbers on stuff next time, it seems odd Foundry wouldn't warn the user something is clearly not up-to-date when the version numbers are mismatched and they check for updates.

Thanks for your patience, I'll have to go through and double check all my modules manually! :)
