### ISSUE TITLE
Special movements for 5e

### ISSUE THREAD

**Issue by DarKDinDoN** [wsaunders1014/ShowDragDistance#28]
Hello,

Not sure if it's a bug.
With the latest version, if a character or a npc has a description as part of the special movement field on 5e. No path is shown when dragging the token.

---

Example:
A npc with these two fields:
- Value: "6 m"
- Special: "Swim 6 m"

Dragging the token doesn't show the path and the colored squares.

---

The previous version used `parseInt()` or 0 to compute the values of `value` & `special`
So:
- `parseInt("6 m") === 6`
- `parseInt("6 m swim") === 6`
- `parseInt("swim 6 m") === NaN / 0`

That had a nice side effect. It showed the path for what it could compute. And that was quite OK. Because Swim and ground movement shouldn't be added up in this situation.

I allowed me to configure the special field these ways:
- "6 m swim" when I wanted to add up special to value but still write a description
- "swim 6 m" when I **didn't** wanted to add up special to value

I was able to configure characters this way:
- Monk pc: {value: "9 m", "special": "4.5 m Unarmored Movement"} and still have the path showing 13.5 m
- some monter fish npc: {value: "6 m", "special": "swim 9 m"} and have the path only showing 6 m because ground movement and swim don't add up

That was not perfect, but that was working.
Any thoughts on that?

**Comment by wsaunders1014** [comment]
I didn't realize that was what went in to the special section. You can just delete the reference to the special section and it won't add it. I'm not sure about metric movement.

**Comment by wsaunders1014** [comment]
I've removed the special component from the max speed calculation.  Since special movement is only for indicating movement like Climbing, Flying,Swimming, etc it doesn't make sense to add it to base speed. You can set a flag though using TokenReference.setFlag('ShowDragDistance','speed',{base:n,dash:n} and it will add that to the base movement speed defined in the settings.
