### ISSUE TITLE
Cannot create waypoint using mac trackpad

### ISSUE THREAD

**Issue by MickCrozier** [wsaunders1014/ShowDragDistance#29]
Hi Will
Using a mac trackpad there is no way to right click without triggering the move.
Is it possible to add a keystroke to set a waypoint aswell?

Cheers,
Mick

**Comment by wsaunders1014** [comment]
Yeah that's a good idea.

**Comment by wsaunders1014** [comment]
check out 2.1.1, pressing p now adds way point

**Comment by MickCrozier** [comment]
Outstanding!!! Thank you!!
