### ISSUE TITLE
Difficulties being able to drag a token back to its original position

### ISSUE THREAD

**Issue by bluesatin** [wsaunders1014/ShowDragDistance#33]
# Information
Foundry Virtual Tabletop — 0.6.6
Show Drag Distance — 2.1.0

# Problem
When dragging a token, there are some weird issues on being able to return the token back to its original position.

With the module enabled, it often sticks to moving 5ft in the direction you approached the token's original tile, unless you wiggle the token around a bunch and it sometimes allows you to drop the token back to its original position. However this is also sometimes buggy and ends up showing no path overlay (indicating the token shouldn't move), but will actually move your token a square in a direction and then leave a little circle overlay (which is what I assume the start of a path overlay).

[Video demonstration of the bug here.](https://gfycat.com/delectablefarawaykouprey)

It might be related to Issue #15 where movement is based upon where you click on the token, but it's not entirely clear.

----

Thanks for your time! :)

**Comment by wsaunders1014** [comment]
This should be addressed as of last update
