### ISSUE TITLE
Using Shift to place the Tokens off the grid doesn't work very well.

### ISSUE THREAD

**Issue by yoshikidneo** [wsaunders1014/ShowDragDistance#36]
I've noticed that with the "Enable Showing Distance on Drag" option checked, when you try to use shift on a token to place it off the grid, it's very finicky. I believe it can only traverse 2 grid squares and no more. What I mean by that is if you try placing a token with shift on a corner of 4 grid squares, it places itself between only 2 of them in between. This then causes it to stay in this off-grid state, so you can move it but it remains in between two grid squares the whole time.

**Comment by wsaunders1014** [comment]
What version are you using?

**Comment by yoshikidneo** [comment]
I think it was just before the update, since it updated it’s been fixed.
