### ISSUE TITLE
GM DragRuler not broadcasting

### ISSUE THREAD

**Issue by Nordiii** [wsaunders1014/ShowDragDistance#37]
The GM Ruler does not always get broadcasted even when ruler broadcast permission is set.
**Data:**
•	FoundryVTT 0.6.6
•	DND5e 0.96
•	ShowDragDistance 2.1.4

**How to reproduce (I used Firefox):**
1.	Create new World
2.	Create second player 
3.	Import a Starter Hero and give the second player owner rights
4.	Enable ShowDragDistance
5.	As GM drag the token of the player
=>	Ruler is not broadcasted

**Other things:**
•	Holding ctrl as GM does draw the ruler from the token and broadcasts it
•	Somehow it works sometimes / can get fixed until the GM reloads. I could not find how though
•	No error is thrown

**Comment by wsaunders1014** [comment]
The GM drag is hidden unless you press Alt.
