### ISSUE TITLE
Tokens take "shortcut" instead of travelling marked out path

### ISSUE THREAD

**Issue by Norc** [wsaunders1014/ShowDragDistance#38]
In the following screenshot, arth should zag around and touch each waypoint before ending up at the destination. Instead, he just moves diagonally one square down and to the right.

![image](https://user-images.githubusercontent.com/64667579/94216609-c8ce9300-fead-11ea-8acf-23139c247e63.png)

This doesn't allow the fog of war to be cleared or allow the token to view on the way. As of 1.6.6 or so, I know Show Drag Distance did trace out the path correctly. 

This "shortcut" behavior happens in both 0.6.6 and 0.7.2 as the only module enabled in a clean Kobold Cauldron world.

**Comment by ExileofBrokenSky** [comment]
Confirmed here as well

**Comment by zaroygr** [comment]
Confirmed

**Comment by wsaunders1014** [comment]
This should be fixed now.
