### ISSUE TITLE
2.1.8 has issue moving tokens on gridless maps

### ISSUE THREAD

**Issue by apoapostolov** [wsaunders1014/ShowDragDistance#46]
On a gridless maps the tokens seem to "snap" at a point lower and right from where I drop them. When selecting multiple and I drag them, they seem to move and shuffle randomly when dropped.

**Comment by GambetTV** [comment]
I'm getting this issue too. It's like they're snapped to a grid that doesn't exist.

**Comment by wsaunders1014** [comment]
this is addressed in 2.1.9
