### ISSUE TITLE
Pivoting Creates weird math

### ISSUE THREAD

**Issue by Avitale34** [wsaunders1014/ShowDragDistance#47]
With the most recent update when you pivot you it creates an off center point that calculates distance incorrectly. it adds an extra 5ft per pivot.

**Comment by wsaunders1014** [comment]
What do you mean by pivot?

**Comment by Avitale34** [comment]
When you right click and create a waypoint.

**Comment by Avitale34** [comment]
![Untitled](https://user-images.githubusercontent.com/65961637/94886547-79560d00-0441-11eb-8757-992b9ab7e999.png)

**Comment by wsaunders1014** [comment]
this is is addressed in 2.1.9
