### ISSUE TITLE
Can no longer drag groups of tokens

### ISSUE THREAD

**Issue by Avitale34** [wsaunders1014/ShowDragDistance#48]
With the newest update you can no longer drag groups of tokens it only pulls one token at a time.

**Comment by GimmeYourShoes** [comment]
I would like to 2nd this issue; not being able to drag groups is a detriment to the GM. Thanks!

**Comment by maxipad1991junkmail** [comment]
This was also an issue in my game.  I can confirm that disabling ShowDragDistance corrects the issue.  I also ran into an issue where if I moved another token it would occasionally go to the spot the last token I'd moved had been moved to, resulting in some really odd behavior.

**Comment by apoapostolov** [comment]
I suggest downloading 2.1.4 via Github and replacing content in the folder in /data/modules/showdragdistance folder, and editing version in json to 2.1.8 so it doesn't update to the problematic issue and wait for @wsaunders1014 to fix the issue.

**Comment by wsaunders1014** [comment]
Should be fixed in 2.1.9
