### ISSUE TITLE
[Enhancement Request] Line of sight tool

### ISSUE THREAD

**Issue by supernovajm** [wsaunders1014/ShowDragDistance#50]
I would like to see support for displaying lines from the corner of a square to the corners of another square for assistance in determining line of sight. This is useful for systems like starfinder which use this to determine if a particular target [has cover](https://www.youtube.com/watch?v=oj7CdFetEro).

**Comment by wsaunders1014** [comment]
DId you mean to leave this on Show Drag Distance module? Issues with LoS are outside the scope of this module.

**Comment by supernovajm** [comment]
Yes I did mean to post it here. I'm not looking for any interaction with walls or LOS. I was just looking for a way to draw lines from one square to another similar to the line used for the move/measure tools, except instead of the line coming from the center of the square, I want lines drawn to the corners.
