### ISSUE TITLE
Incompatibility with the Show Art module due to the use of the X key

### ISSUE THREAD

**Issue by Fraxinus1753** [wsaunders1014/ShowDragDistance#55]
Hi, there is an incompatibility with Zeel's Show Art module. Show Art is supposed to broadcast a selected token's art to players when pressing shift + X. However, this doesn't work with Show Drag Distance enabled (nothing happens). I commented on this issue in the Show Art module and it appears it can be solved only in Show Drag Distance, as it's due to the fact that Show Drag Distance uses X to cancel a token's planned movement.

Would there be a way to solve this, for instance by introducing a way to remap movement cancellation to another key or to disable it completely in the settings? Thanks!

**Comment by wsaunders1014** [comment]
Fixed
