### ISSUE TITLE
Incompatibility with the Pointer module due to the use of the X key

### ISSUE THREAD

**Issue by apoapostolov** [wsaunders1014/ShowDragDistance#56]
This may be related to #55 as well. Since Pointer switched to using X button a while ago, the two mods are now having conflict. 

If this feature had X delete functionality as an optional setting, it would have not caused the issue. Personally I never use X to delete the distance, nor any of my players. So it is not really that useful. 

![image](https://user-images.githubusercontent.com/4083812/95991515-886f8e80-0e35-11eb-875e-22fa57a8be1e.png)

**Comment by wsaunders1014** [comment]
This should be fixed
