### ISSUE TITLE
Set Way Points (Enhancement)

### ISSUE THREAD

**Issue by muehf** [wsaunders1014/ShowDragDistance#6]
It would be great if I could set waypoints. Maybe the standard ruler behaviour could be used: Hold Control and press left mouse button to set a waypoints. In this case the current CTRL function of the module might be remapped to SHIFT or ALT.

But I would also like to set waypoints using the right mouse button.

**Comment by wsaunders1014** [comment]
You can now drag token and right click to place waypoints. while holding ctrl on the map with a token selected you can also set waypoints with the rangefinder.
