### ISSUE TITLE
Movement variant rule calculation doesn't work with waypoints

### ISSUE THREAD

**Issue by DarKDinDoN** [wsaunders1014/ShowDragDistance#60]
Hello,

When using the 5e variant for movement (1.5 / 3 / 1.5 ...) and adding multiple waypoints the calculation is wrong.
![image](https://user-images.githubusercontent.com/1687854/97696891-8567d580-1aa6-11eb-9a1b-4373722c320c.png)

As you can see on the image, for each diagonal I add a waypoint. And for each waypoint the diagonal movement calculation seems to be reset.

Ruler should not diplay : 1.5 / 1.5 / 1.5 / 1.5/ 1.5 / 1.5
But : 1.5 / 3 / 1.5 / 3 / 1.5 / 3

Same behavior with feet (5)

**Comment by wsaunders1014** [comment]
This is should be addressed now.
