### ISSUE TITLE
ShowDragDistance 2.2.1 displays colored hex tile offset from the token location.

### ISSUE THREAD

**Issue by intemptesta** [wsaunders1014/ShowDragDistance#61]
FoundryVTT 0.7.5
ShowDragDistance 2.2.1

The colored tiles display offset to the top left, about 5 tiles away from token.

![image](https://user-images.githubusercontent.com/13413266/98155672-389e5780-1f09-11eb-81fe-c8ed4d096bc1.png)

**Comment by wsaunders1014** [comment]
This has been addressed
