### ISSUE TITLE
Module no longer allows shift-dragging to random locations (auto-snapping to grid).

### ISSUE THREAD

**Issue by metalheadzaid** [wsaunders1014/ShowDragDistance#63]
Previously the module would allow me to move to any location by holding shift (and showed measurement for that) allowing for better alignment for static tokens with the background. Now it is auto snapping to grid preventing such behavior. I've had it work a few days ago with A LOT of coaxing, but with module disabled moving to a non-grid location works perfectly.

**Comment by wsaunders1014** [comment]
hmm yeah I made some changes to how often the measure function fires to optimize, but I forgot to account for drag shifting

Change line 73 of showdragdistance.js to this:
```
 if(lastX != x || lastY !=y  || dragShift){
```

**Comment by wsaunders1014** [comment]
Also just pushed another release with it in it.

**Comment by metalheadzaid** [comment]
Resolved, thanks!
